import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Solana",
  description: "Generated by create next app",
  keywords: ["Solana", "tailwindcss", "gsap", "nextjs", "react"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white font-[Helvetica] min-w-screen min-h-screen">
        {children}
      </body>
    </html>
  );
}
